name: mobile
description: "SAuth Mobile Application"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  device_info_plus: ^11.5.0
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  shared_preferences: ^2.5.3
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
